export { default as Main } from './Main/Main'
export { default as ProjectPage } from './Project/ProjectPage'
export { default as ResumePage } from './Resume/ResumePage'
export { default as LoginPage } from './Login/LoginPage'
export { default as AdminPage } from './Admin/AdminPage'